try:
    foobar
except:
    print("PROBLEM")
print("after the try")